declare @sSirket table(No int)
insert into @sSirket
select 30


declare @sAmbar table(No int)
insert into @sAmbar
select 33


SELECT
I.CODE AS 'URUN_KODU' ,
I.NAME AS 'URUN_ADI',
CAP.NAME,
(SELECT TOP 1 UNITSTL.CODE  FROM  
                         dbo.LG_XXX_UNITSETF AS UNITSTF INNER JOIN  dbo.LG_XXX_UNITSETL AS UNITSTL ON UNITSTF.LOGICALREF = UNITSTL.UNITSETREF 
                         INNER JOIN  dbo.LG_XXX_ITEMS AS ITEMS ON UNITSTF.LOGICALREF = I.UNITSETREF ) AS BIRIM,

SUM((CASE WHEN S.IOCODE in (1,2) THEN COALESCE(
CASE S.UINFO1
WHEN 0 THEN S.AMOUNT
ELSE S.AMOUNT*S.UINFO2/S.UINFO1
END, S.AMOUNT) ELSE 0 END)
) 
 AS 'ToplamGiris',

SUM((CASE WHEN S.IOCODE not in (1,2) THEN COALESCE(
CASE S.UINFO1
WHEN 0 THEN S.AMOUNT
ELSE S.AMOUNT*S.UINFO2/S.UINFO1
END, S.AMOUNT) ELSE 0 END)
) 'ToplamCikis',
(--giris-cikis farký alýndý
select (
SUM((CASE WHEN S.IOCODE in (1,2) THEN COALESCE(
CASE S.UINFO1
WHEN 0 THEN S.AMOUNT
ELSE S.AMOUNT*S.UINFO2/S.UINFO1
END, S.AMOUNT) ELSE 0 END)
) 
-
SUM((CASE WHEN S.IOCODE not in (1,2) THEN COALESCE(
CASE S.UINFO1
WHEN 0 THEN S.AMOUNT
ELSE S.AMOUNT*S.UINFO2/S.UINFO1
END, S.AMOUNT) ELSE 0 END)
) 

) )AS 'MevcutStok'

--donembasimiktar=TOPLAMGIRIS-TOPLAMCIKIS

from LG_XXX_ITEMS AS I 
LEFT JOIN LG_XXX_01_STLINE AS S ON I.LOGICALREF=S.STOCKREF AND I.ACTIVE='0' and S.CANCELLED='0' 
LEFT JOIN LG_XXX_01_INVOICE AS F ON S.INVOICEREF=F.LOGICALREF 
LEFT JOIN LG_XXX_01_STFICHE SF ON  SF.LOGICALREF=S.STFICHEREF 
LEFT JOIN LG_XXX_01_STINVTOT AS ST ON I.LOGICALREF=ST.STOCKREF
LEFT JOIN LOGODB.DBO.L_CAPIWHOUSE AS CAP ON CAP.NR=S.SOURCEINDEX
where SF.BRANCH IN(SELECT no  FROM @sSirket)
AND 
CAP.FIRMNR=XXX
and
CAP.NR IN(SELECT no  FROM @sAmbar)
GROUP BY I.CODE,I.NAME,I.STGRPCODE,I.SPECODE,I.LOGICALREF,I.UNITSETREF,CAP.NAME
Order By I.CODE

